#!/bin/bash

diff=$(cargo fmt -- --check)
result=$?

if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some code style issues, run `cargo fmt` first.
EOF
    exit 1
fi

diff=$(cargo clippy --all-features --all-targets)
result=$?

if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some clippy issues, run `cargo clippy --all-features --all-targets` first.
EOF
    exit 1
fi

exit 0
